import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { StatusBadgeComponent } from '../../../shared/components/status-badge/status-badge.component';
import { DataService } from '../../../core/services/data.service';
import { UserCreateRequest, UserSummaryResponse } from '../../../core/models/user.models';
import { ROLES, Role, UserStatus } from '../../../core/models/enums';
@Component({ selector:'app-users', standalone:true, imports:[FormsModule, StatusBadgeComponent], template:`
<section class="page"><div class="page-header"><div><h1 class="page-title">Utilisateurs</h1><p class="page-subtitle">Gestion des rôles ADMIN, MANAGER, AGENT et CLIENT.</p></div></div>
<div class="card"><h3>Créer utilisateur interne</h3><form class="form-grid" (ngSubmit)="create()"><input name="fn" placeholder="Prénom" [(ngModel)]="form.firstName"><input name="ln" placeholder="Nom" [(ngModel)]="form.lastName"><input name="email" placeholder="Email" [(ngModel)]="form.email"><input name="tel" placeholder="Téléphone" [(ngModel)]="form.phoneNumber"><select name="role" [(ngModel)]="form.role">@for(r of roles; track r){<option [value]="r">{{r}}</option>}</select><input name="agency" type="number" placeholder="Agency ID" [(ngModel)]="form.agencyId"><button class="btn primary">Créer</button></form></div>
<div class="card table-wrap"><table><thead><tr><th>ID</th><th>Nom</th><th>Email</th><th>Rôle</th><th>Statut</th><th>Agence</th><th>Action</th></tr></thead><tbody>@for(u of users; track u.id){<tr><td>{{u.id}}</td><td>{{u.fullName}}</td><td>{{u.email}}</td><td>{{u.role}}</td><td><app-status-badge [value]="u.status"/></td><td>{{u.agencyName}}</td><td><button class="btn" (click)="toggle(u)">Activer/Suspendre</button></td></tr>}</tbody></table></div></section>`})
export class UsersComponent implements OnInit{ roles=ROLES; users:UserSummaryResponse[]=[]; form:UserCreateRequest={firstName:'',lastName:'',email:'',phoneNumber:'',role:'ROLE_AGENT',agencyId:1}; constructor(private data:DataService){} ngOnInit(){this.load()} load(){this.data.users().subscribe(x=>this.users=x)} create(){this.data.createUser(this.form).subscribe(()=>{this.form={firstName:'',lastName:'',email:'',phoneNumber:'',role:'ROLE_AGENT',agencyId:1};this.load()})} toggle(u:UserSummaryResponse){const status:UserStatus=u.status==='ACTIVE'?'SUSPENDED':'ACTIVE';this.data.updateUserStatus(u.id,status).subscribe(()=>this.load())}}
