package ma.ensam.okanetransfer.enums;

public enum AuditAction {
    LOGIN,
    LOGOUT,
    CREATE_TRANSFER,
    PAY_TRANSFER,
    CANCEL_TRANSFER,
    UPDATE_RATE,
    UPDATE_FEE_GRID,
    KYC_REVIEW,
    AML_REVIEW,
    CASH_CLOSING,
    USER_CREATED,
    USER_SUSPENDED,
    USER_ACTIVATED,
    MOBILE_MONEY_SEND,
    MOBILE_MONEY_CALLBACK,
    MOBILE_MONEY_RECONCILE
}
